### ISSUE TITLE
Characters get cut off between pages in a text box.

### ISSUE THREAD

**Issue by danadrew** [moai/moai-dev#400]
See sample in integration : samples/test/textbox-paging7

On textboxes that have multiple lines, a few characters are getting lost between pages. Press spacebar in the sample to go to the next page. Doesn't happen when paging from the last page to the first page.

**Comment by patrickmeehan** [comment]
Should be fixed now...

**Comment by danadrew** [comment]
It's better but I'm still finding some characters missing. In the sample, the second page is missing a 2 at the very beginning. It should say "2pages" and right now it says "pages".

I added another sample where 3 characters still get cut off into the same main.lua file. You can switch between the two samples by changing the function call on the last line of the file.

**Comment by patrickmeehan** [comment]
OK, try it now...

**Comment by patrickmeehan** [comment]
trello
